# Generated by Django 3.0.5 on 2020-09-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Large machine', 'Large machine'), ('Small machine', 'Small machine'), ('Espresso machine,', 'Espresso machine,')], max_length=100)),
                ('model', models.CharField(choices=[('base model', 'base model'), ('premium model', 'premium model'), ('deluxe model', 'deluxe model,')], max_length=100)),
                ('water_line_compatible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Large coffe pod', 'Large coffe pod'), ('Small coffe pod', 'Small coffe pod'), ('Espresso pod,', 'Espresso pod,')], max_length=200)),
                ('coffe_flavor', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Caramel', 'Caramel'), ('psl', 'psl'), ('Mocha', 'Mocha'), ('Hazelnut', 'Hazelnut')], max_length=100)),
                ('pack_size', models.CharField(choices=[('1 dozen ', '1 dozen '), ('3 dozen ', '3 dozen '), ('5 dozen ', '5 dozen '), ('7 dozen ', '7 dozen ')], max_length=100)),
            ],
        ),
    ]
